POST http://localhost:8095/api/auth/logout
Content-Type: application/x-www-form-urlencoded
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODA5NVwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTU5NTA2Nzk2OCwiZXhwIjoxNTk1MDcxNTY4LCJuYmYiOjE1OTUwNjc5NjgsImp0aSI6InJWWThZZ0hxa3FGdnRyMUMiLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.p4GZ0wtSjWlNILbLiQa0sZfMuio0kpdcimOgmp9kai8
