POST http://localhost:8096/api/auth/me
Content-Type: application/x-www-form-urlencoded
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODA5NlwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTY0Mjg0MTk1OCwiZXhwIjoxNjk0NjgxOTU4LCJuYmYiOjE2NDI4NDE5NTgsImp0aSI6InZjd3VIdXQyYzFiOUtHNE0iLCJzdWIiOiIzIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.Uua27vVpYb-jQqWBajZVqnxu1AH0WaoYVS8Yg3Ji0lg
