POST http://localhost:8095/api/auth/refresh
Content-Type: application/x-www-form-urlencoded
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODA5NVwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTU5NTA2ODEyMywiZXhwIjoxNTk1MDcxNzIzLCJuYmYiOjE1OTUwNjgxMjMsImp0aSI6IlNjbGJnNklEUFIyT0FlWWwiLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.8bNL_z_fOm945vfs2ZOJVKY2aVGUeWWIfxC9CF_XouE

