GET http://localhost:8096/api/reports/total_enquiries
Content-Type: application/x-www-form-urlencoded
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODA5NlwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTY0NDA2ODMzMSwiZXhwIjoxNjQ0MTU0NzMxLCJuYmYiOjE2NDQwNjgzMzEsImp0aSI6IjJVcERTSDZxZHpkZ2dzMXEiLCJzdWIiOiIzMTQyIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.eNZ67zP93frKVAKi8efzb4tXY5X6LVXFHh-8ulmZ02s
