GET http://localhost:8095/api/roles?paginate=0
Content-Type: application/x-www-form-urlencoded
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODA5NVwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTU5NjM2NTQ4OCwiZXhwIjoxNTk2MzY5MDg4LCJuYmYiOjE1OTYzNjU0ODgsImp0aSI6InNtSkRDWlBmY0pKa2xQNmsiLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.N2G4C35SVCajgk2TRJo2j8eeBjtWlzxIuMAyPnNsJpA
