GET http://localhost:8095/api/users
Content-Type: application/x-www-form-urlencoded
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODA5NVwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTU5NjM1NTM0NiwiZXhwIjoxNTk2MzU4OTQ2LCJuYmYiOjE1OTYzNTUzNDYsImp0aSI6IjVhNHNabVB6aTh2VEtZRjQiLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.MLpqxZYtBBhxMXGbrHSE1O428bzpjmB9auaxKGLKO1I

