GET http://localhost:8095/api/user
Content-Type: application/x-www-form-urlencoded
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODA5NVwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTU5NTA2ODM1NCwiZXhwIjoxNTk1MDcxOTU0LCJuYmYiOjE1OTUwNjgzNTQsImp0aSI6IlNLQnRtMU14UW1haGJOcVoiLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.pwaTfNO7ss7h3fQ5A74osJG8fmNMHf68ef1wyO7O7mo
